# deduplicate path variables if they end up happening
typeset -U PATH

# akshay git aliases
alias akdsm="git branch --merged | grep -v \"*\" | grep akd"
alias akdcm="git branch --merged | grep -v \"*\" | grep akd | xargs git branch -d"
