if [ -x /usr/libexec/path_helper ]; then
    eval $(/usr/libexec/path_helper -s)
fi

# akshay git aliases
alias akdsm="git branch --merged | grep -v \"*\" | grep akd"
alias akdcm="git branch --merged | grep -v \"*\" | grep akd | xargs git branch -d"

# gcloud completions
source "$(brew --prefix)/share/google-cloud-sdk/path.zsh.inc"
source "$(brew --prefix)/share/google-cloud-sdk/completion.zsh.inc"
